### ISSUE TITLE
API Down

### ISSUE THREAD

**Issue by klamouri** [killerwhile/kafka-assignment-optimizer#2]
Hi,
Not sure if there is another place to ask this but it seems like the API is down, any chance of getting this fixed and maybe open source the code, for future outages on the API?

Thanks a lot :)

**Comment by killerwhile** [comment]
Thanks for reaching out. I made sure the API is up again. Unfortunately we never got the green light to opensource the tool. I tried my best to make it available, and I can only promise I'll go into another request round... Sorry.

**Comment by klamouri** [comment]
Thanks @killerwhile I appreciate you fixing the API. This tool is the best I've found as a drop-in replacement for optimized re-assignements. It checks all the important optimization parameters: rack, topic distribution, leader optimization, .... I hope this time you'll be successful to get the green light 😉
